### PR TITLE
Rename "Action" to "Sidebar" across the extension

### PR DESCRIPTION
**Pull request by fregante**
I wanted to try a small refactoring as described in https://github.com/pixiebrix/pixiebrix-extension/issues/2672 and https://www.notion.so/pixiebrix/Internal-External-Refactoring-0d313622452c4db38e039feab37d7ab2

I presume the word "action" was used across the extension because the browser calls the button `browserAction`, but what happens after one presses the button is up to us: In this case, we show a **sidebar**.

This PR only renames files and their references across the extension, except those that are literally about the `browserAction` button.

## Before merge

- [ ] Update branch to ensure CI passes

### CODE REVIEW

**Comment by fregante** [comment]
I think a migration is needed indeed:

Screen Shot 21

Seen on `options.html#/installed`

**Comment by twschiller** [comment]
This PR is definitely a step in the right direction, but will require corresponding changes to also be made on the backend.

I would suggest we leave the YAML/Schema alone in the first PR, bur refactor the code

Otherwise we won't be able to merge until later this week at the earliest due to other more pressing work

**Comment by fregante** [comment]
> I would suggest we leave the YAML/Schema alone in the first PR, bur refactor the code

Good point, I reverted the schema changes so this PR should only change:

- file names
- variable names
- some user strings/errors

**Review by twschiller — APPROVED** [review]

**Comment by twschiller** [comment]
image

**Pull request merged**
