### PR TITLE
Fix type error when pinning 2.1.4 extension to app

### PR DESCRIPTION
**Pull request by fungairino**
## What does this PR do?

- Fixes a minor type error preventing pinning the extension version in app: https://github.com/pixiebrix/pixiebrix-app/pull/5846
- Confirmed this fixes the type issue in app by pinning the version in this branch using `❯ npm run update-extension -- pin-2.1.4`

## Discussion

- Didn't investigate too deeply as to why this type error didn't pop up earlier in extension, likely due to slight tsconfig differences.

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

**Review by twschiller — APPROVED** [review]

**Review by johnnymetz — APPROVED** [review]

**Comment by twschiller** [comment]
@johnnymetz @fungairino is the plan to wait until the 2.1.5 release is cut? Or to pin to a separate branch that has this fix in it?

cc @grahamlangford

**Comment by johnnymetz** [comment]
No strong preference. I say we pin now to prevent the App from falling too far behind (unless there's something since 2.1.4 that may be risky to pin now).

**Comment by johnnymetz** [comment]
I just pinned the App PR to the latest Extension commit: https://github.com/pixiebrix/pixiebrix-app/pull/5846

**Comment by grahamlangford** [comment]
> @johnnymetz @fungairino is the plan to wait until the 2.1.5 release is cut? Or to pin to a separate branch that has this fix in it?

> No strong preference. I say we pin now to prevent the App from falling too far behind (unless there's something since 2.1.4 that may be risky to pin now).

I used to be more concerned about pinning a non-release version. But with the implementation of Playwright in Extension, I trust `main` more than I used to

@johnnymetz we should look at updating the repinning action. I'm pretty sure it tries to repin to the latest tag even if App is currently pinned to a more recent commit of Extension. It would be nice to skip in that case

**Comment by johnnymetz** [comment]
> I'm pretty sure it tries to repin to the latest tag even if App is currently pinned to a more recent commit of Extension. It would be nice to skip in that case

Yes, we have a bug ticket for that (but it's now closed due to being stale): https://github.com/pixiebrix/pixiebrix-app/issues/5270

**Pull request merged**
