### PR TITLE
#8789 object extensibility error

### LINKED ISSUE #8789: Object extensibility error running text snippet
## Describe the bug

- Error running text snippet

## Actual behavior

image

## Additional context

- Observed with text snippet manager mod
- PixieBrix version: `v2.0.5-alpha.3` (bug not present in `alpha.2`)

### PR DESCRIPTION
**Pull request by fungairino**
## What does this PR do?

Fixes #8789

This PR introduces error handling in the `reportEvent` function in the `reportEvent.ts` file. It wraps the `_record` function call in a try-catch block and reports any errors that occur using the `reportError` function. 

It also modifies the `mapEventDataToDeprecatedTerminology` function in the `telemetryHelpers.ts` file to avoid mutating the input data object. It creates a deep clone of the input data object and performs the mapping operations on the cloned object.

### CODE REVIEW

**Comment by twschiller** [comment]
Should be quick to add a test that uses `Object.freeze` that replicates the fix

**Review by grahamlangford — APPROVED** [review]

**Comment by fungairino** [comment]
> Should be quick to add a test that uses Object.freeze that verified the deep clone fix

This is the type of thing that should be caught by an eslint rule, not by a unit test. Looking into that in a following rev.

**Comment by twschiller** [comment]
> This is the type of thing that should be caught by an eslint rule

What are you thinking there? Eslint could warn on argument mutation (if we have a rule to never mutate arguments). But it still wouldn't catch whether or not a frozen object or sub-object could actually make its way to a method

**Comment by fungairino** [comment]
> Eslint could warn on argument mutation (if we have a rule to never mutate arguments)
That's what I'm thinking of.

> It still wouldn't catch whether or not a frozen object or sub-object could actually make its way into a setter
Theoretically this scenario should be caught by TS if we had stricter typing.

**Comment by twschiller** [comment]
> Theoretically this scenario should be caught by TS if we had stricter typing.

IIRC, the type rule is harder than you think. The base assumption is that anything could contain a property/sub-property that is frozen. So you'd have to pretty much ban mutation on anything that's not known to be deep cloned (or an immer draft)

**Pull request merged**
