### PR TITLE
#7680: Add `platform` to `noCrossBoundaryImports` lint rule

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/7680
- Requested by @twschiller  in https://github.com/pixiebrix/pixiebrix-extension/pull/7650
- Brings the amount of warnings from 111 to 144
  - `import "@/platform"`: 33 warnings
  - `import "@/<other boundary>"` in `src/platform/`: 0 warnings

## Demo

Here are some imports that are detected:

https://github.com/pixiebrix/pixiebrix-extension/blob/f0a6036008bd199a59ed969208e147a9dbf30235/src/background/backgroundPlatform.ts#L18

https://github.com/pixiebrix/pixiebrix-extension/blob/f0a6036008bd199a59ed969208e147a9dbf30235/src/bricks/effects/sidebar.ts#L31-L34

## Future work

- [x] Also forbid `messenger` imports (maybe via negative `allowedGlobs`?)

## Checklist

- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

**Comment by twschiller** [comment]
@fregante I think we want to be more discerning here.

The following are OK:
- Importing CONTENT_SCRIPT_CAPABILITIES, PlatformCapability
- Importing types and type helpers, e.g., PlatformProtocol, etc.
- Having webext contexts import from `@/platform` (vice versa should not be allowed though)

Perhaps we want to add an `@/platform/api/` folder? Or it might be simplest to move the safe code to `@/types` directory? What do you recommend?

**Comment by fregante** [comment]
Types are already excluded, in that code only one export is marked. 

> OK: Having webext contexts import from @/platform 

Oh, if the entirety of `@/platform` is meant to be a "shared" folder, then we don't need to make any changes. The rule already covers "don't import from these boundaries (background, contentScript, etc)"

**Comment by fregante** [comment]
I think this is what you wanted:

- `@/platform` files cannot import from those boundaries: ERROR instead of WARN
- `@/platform` files cannot import Messenger files either

**Comment by twschiller** [comment]
👍  Checked it out, and looks correct at first glance

**Review by twschiller — APPROVED** [review]

**Pull request merged**
