### PR TITLE
#5122 Eliminate redundant /api/me/ calls

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

- Part of #5122 
- Use cached `/me` data

## Demo

image

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

**Comment by twschiller** [comment]
Checking my understanding here. The idea is that `RequireAuth` is the only component that actually makes the remote query?

**Comment by BALEHOK** [comment]
> Checking my understanding here. The idea is that RequireAuth is the only component that actually makes the remote query?

@twschiller, correct.

From this ticket I see that we can (need to) improve dev ex by:
1. making it clear that `useGetMeQuery` should not be used. we have to opt for the Auth slice or RTK queries which do not make API request
2. simplifying the tests. mocking RTK API becomes a pain. 80% of time for this task I spent updating the tests. I think we can create a global `appApi` mock and adjust it when needed. also it makes sense to have a shared helper that initializes the auth for a test (a generalized version of `mockMeQuery`).

**Comment by twschiller** [comment]
> simplifying the tests. mocking RTK API becomes a pain. 80% of time for this task I spent updating the tests.

Yep, those changes didn't look fun 😞. @mnholtz @alanb43 this might be a good area for @alanb43 to help out with?

**Review by twschiller — APPROVED** [review]

**Comment by mnholtz** [comment]
> Yep, those changes didn't look fun 😞. @mnholtz @alanb43 this might be a good area for @alanb43 to help out with?

Created a quick issue for this here: https://github.com/pixiebrix/pixiebrix-extension/issues/5159

And tagged @alanb43

**Pull request merged**
