### PR TITLE
Improve input field contrast in extension console and app

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes https://pixiebrix.slack.com/archives/C03CA2M4RCM/p1708961525481959

## Before/after

Screenshot 17

Screenshot 16

## App before/after

before

after

## Checklist

- [x] Designate a primary reviewer: @Misha

### CODE REVIEW

**Review by BrandonPxBx — APPROVED** [review]
Looks good 👍 thanks Federico!

**Comment by mnholtz** [comment]
@fregante I think you tagged the wrong primary reviewer 😆

**Review by mnholtz — APPROVED** [review]

**Comment by fregante** [comment]
I tagged you because those lines were written by you I think 😁 but all good

**Comment by mnholtz** [comment]
> I tagged you because those lines were written by you I think 😁 but all good

No i mean, you tagged `@misha` which isn't my gh handle haha

**Comment by fregante** [comment]
Oopps!

**Pull request merged**
