### PR TITLE
Remove remaining usages of `useQueryState`

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Precursor change to this PR: #7480
- Extracted the changes here to make reviewing easier
- Unified the method for mocking ("me") users
- Cleaned up a bunch of old tests using out-dated testing styles with redux etc.
- Cleans up some shared logic with brick icons

## Reviewer Tips

- Look at all the places where `useQueryState` was converted to just `use*Query` calls
- Look at the brick/marketplace icon changes
- Look at the `userMocks` file
- Maybe look through all the test cleanup/updates if you feel like it

## Checklist

- [x] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer - @grahamlangford

### CODE REVIEW

**Review by grahamlangford — APPROVED** [review]

**Comment by twschiller** [comment]
@BLoe you'll just need to address the merge conflicts

**Comment by grahamlangford** [comment]
@BLoe see merge conflicts

**Comment by BLoe** [comment]
Added @fungairino here because I had to resolve conflicts with some changes to the `useTheme` tests.

**Comment by BLoe** [comment]
> Added @fungairino here because I had to resolve conflicts with some changes to the `useTheme` tests, I don't think I broke anything you did, but just wanted to make sure.

I'm going to merge this now, but happy to open a new PR and make changes if you end up having any comments here.

**Pull request merged**
