### PR TITLE
#6796: Replace custom lint rule for `getExtensionConsoleUrl`

### PR DESCRIPTION
**Pull request by fregante**
- Follow-up to https://github.com/pixiebrix/pixiebrix-extension/pull/6796#issuecomment-1789080285

@twschiller

### CODE REVIEW

**Review by twschiller — APPROVED** [review]
Just curious, how did you figure out the incantation required to get the rule to work? (E.e., common patterns) Is there a helpful guide somewhere we can share with the engineering team?

**Comment by twschiller** [comment]
cc @BLoe as a FYI since he's worked on other eslint rules

**Comment by fregante** [comment]
There's a partial guide on eslint's website but I think you'd have to be comfortable with code parsing and AST to actually write something from scratch. 

For this selector:

1. I asked Copilot, which produced a non-working selector
2. Then I made it as small as possible until it matched `getURL`
3. Then with a bit of trial and error I added more conditions
4. Then I saw that they almost matched the rule you/ChatGPT wrote so I was able to match the entire call

**Comment by BLoe** [comment]
I agree that might be an easier way to add tests for our custom lint rules over using the RuleTester

**Comment by BLoe** [comment]
> 1. I asked Copilot, which produced a non-working selector

CoPilot ftw! 😂

**Pull request merged**
