### PR TITLE
#814: optimistically load main page editor screen

### LINKED ISSUE #814: The editor should not show the intermediary "Welcome" page every time
Every time I open the editor I'm fooled into thinking I have to fill in the form on the **Welcome screen**, but it's actually just loading the next screen.

slow

Improvements possible:

- [ ] don't show this screen while checking (I think it should ever only be shown on the first install)
- [ ] performance! It takes a few second from the click until the final page loads, sometimes even more than a few. What's holding the welcome page for so long?

### PR DESCRIPTION
**Pull request by twschiller**
@fregante I think this should fix the problem enough. If not, we'll have to look at caching the author scope on the background page

Closes #814

### CODE REVIEW

**Comment by fregante** [comment]
Yes, this feels much faster! One thing to note is that this changes the logic unexpectedly: Until now I haven't been able to connect on Firefox, but that welcome screen was skipped anyway. With this change I can no longer get past it.



Maybe it's not a real issue though.

## Main

https://user-images.githubusercontent.com/1402241/126043638-d0a9e0b7-afc7-44c5-af4f-4ef5d592e315.mov


## This PR



https://user-images.githubusercontent.com/1402241/126043593-f1b3f89c-4f07-47b8-bcc8-3ac9c7914e0a.mov

**Comment by fregante** [comment]
I just remembered I can use the local-only mode in Firefox and that still works.

**Comment by twschiller** [comment]
> One thing to note is that this changes the logic unexpectedly

This PR doesn't touch that setup screen. I suspect that the behavior you're seeing might be unintentionally caused by a server changes: https://github.com/pixiebrix/pixiebrix-app/pull/242

If the current behavior is annoying for you please open a ticket

**Comment by fregante** [comment]
Yeah this PR blocks me in Firefox, but any of these would also unblock me:

- https://github.com/pixiebrix/pixiebrix-app/issues/202
- https://github.com/pixiebrix/pixiebrix-extension/issues/835

https://github.com/pixiebrix/pixiebrix-app/pull/242 didn't affect me before this PR

**Comment by twschiller** [comment]
> Yeah this PR blocks me in Firefox

Apologies! Here's a PR to revert: https://github.com/pixiebrix/pixiebrix-extension/pull/836. You should be able to merge it once you've approved it. I have to run and will be back in a couple hours

**Comment by fregante** [comment]
Thank you! I'll merge it later if required, I can probably work around it locally for the time being. The other 2 issues are _also_ possibly blocking me anyway. Now sure how much longer I'll work today.

**Pull request merged**
