### PR TITLE
removes no-unnecessary-type-assertion eslint disables 

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Removes all of the `no-unnecessary-type-assertions` eslint disables
- During the strict null checks migration, we had to disable `no-unnecessary-type-assertions` in several places to appease the two disparate type configs

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

**Comment by fungairino** [comment]
Me reading this PR

**Review by fungairino — APPROVED** [review]

**Comment by twschiller** [comment]
image

**Comment by twschiller** [comment]
@grahamlangford tests failed again on both Chrome/Edge so those are actually likely failures

**Comment by grahamlangford** [comment]
> @grahamlangford tests failed again on both Chrome/Edge so those are actually likely failures

Bizarre, because I don't see how removing non null assertions would impact runtime, but somehow it must be. I"ll look into it

**Pull request merged**
