### PR TITLE
#572: revert externalSendMessage changes

### LINKED ISSUE #572: Fix externalSendMessage method for messaging from PixieBrix app
When calling from the external site, we have to use the chrome API namespace because Mozilla's browser polyfill is only active in extension contexts:

http://github.com/pixiebrix/pixiebrix-extension/blob/a43af4d05a084a049c6707605453955010a2bbad/src/background/protocol.ts#L140-L140

### PR DESCRIPTION
**Pull request by twschiller**
Closes #572

### CODE REVIEW

**Comment by fregante** [comment]
I don't get it, but if it fixes an error for you then 👍 

Maybe this should be reported to https://github.com/mozilla/webextension-polyfill

Is the issue currently on production? How can I replicate it?

The only issue I limitation I see on their side is:

https://github.com/mozilla/webextension-polyfill/blob/4b2afe89fd64bd2357511a98593ccc4628d58b47/src/browser-polyfill.js#L543

**Review by fregante — APPROVED** [review]
It looks like that's exactly the line that affected it:

```js
typeof chrome != "object" || !chrome || !chrome.runtime || !chrome.runtime.id
```

This is `true` on Chrome on `app.pixiebrix.com`

We do have `chrome` and `chrome.runtime`, but not `chrome.runtime.id`

**Comment by twschiller** [comment]
> It looks like that's exactly the line that affected it:

Thanks for looking into this! The context is I'm working on some updates to `app.pixiebrix.com` including updating the extension dependency

I'll merge in this change, and open an issue on `mozilla/webextension-polyfill` about that runtime.id check

**Comment by fregante** [comment]
Done: https://github.com/mozilla/webextension-polyfill/issues/326

**Pull request merged**
