### PR TITLE
#540: prevent multiple content script injections

### PR DESCRIPTION
**Pull request by twschiller**

### CODE REVIEW

**Comment by fregante** [comment]
It sounds like this should never happen here: You’re already targeting the dom-loaded event and that supposedly only happens once per page load. If scripts are being injected twice it’s more likely that the register function is being called twice. 

Also my updated loadCheck in https://github.com/fregante/content-scripts-register-polyfill/pull/15 should prevent this from happening:

1. Call 1, loadCheck queued
2. Call 2, loadCheck queued
3. Call 1, loadCheck executed, return false
4. Call 2, loadCheck executed, return false
5. Call 1, set loadCheck queued
6. Call 2, set loadCheck queued
7. Etc

What I should probably do, whether or not this is the case, is prevent duplicate **registrations** if the native one does that.

**Comment by fregante** [comment]
> Our webext-dynamic-content-scripts is still pinned to 7.0.0 in the package-lock

I reviewed the changes since then, they should not affect PB usage (other than changes on the register polyfill)

I suppose this is happening because there are 3 ways to inject the content script and they don't use the same exact mechanism

- `contentScript.register`, via `webext-dynamic-content-scripts` uses `loadCheck`
- `injectContentScript` uses PING, which depends on `markReady`, which is called after a few promises

I'll add an export to my polyfill so that it can be used to inject scripts the same exact way, without checking for permanent permissions

**Comment by fregante** [comment]
> I'll add an export to my polyfill so that it can be used to inject scripts the same exact way, without checking for permanent permissions

On second thought, that would cover it on Chrome, but Firefox would not use the same injection function for the registration, so we'd be back to square one.

I think the delayed `markReady` is the problem here. Since `contentScript.js` is injected by multiple parts in various ways, it should have its own duplicate detection, which should be as easy as starting the file with something like:

```js
if (!window.pbLoaded) {
	init();
}
window.pbLoaded = true;
```

This won't prevent the unnecessary `executeScript` calls and the parsing of the `contentscript.js` file, but the code won't be executed twice.

**Comment by fregante** [comment]
I hid my previous comments because I think I know what's going on:

1. dynamic-scripts registers the script as usual
2. one of the other injectors may or may not detect that this has been injected, and inject again
3. `PIXIEBRIX_SYMBOL` prevents double execution and indeed it detects itself

However the problem is that this last step only stops the current file from executing. Other modules that have been imported are still executed and might attach their own handlers.

This is shown by the React comment here and the "COOL BEANS" log I appended to `extensionContext.ts`, which indeed appears before the "already installed" error.

Screen Shot 11

### Solution

We can reduce duplicate injections by using the same `loadCheck` code from my polyfill, but we can't completely eliminate it (in Firefox for example).

Since we can't fully prevent them, we need to ensure that the code **actually** doesn't run by either:

- going through every dependency of `contentScript.ts` to ensure it doesn't have any side effects, or
- turn `contentScript.ts` into a detect + load micro-module:
	```js
	if (/* our duplicate detection code */) {
		import('./actualContentScript');
	} else {
		throw Error(`PixieBrix contentScript already installed`);
	}
	```

**Comment by twschiller** [comment]
> one of the other injectors may or may not detect that this has been injected, and inject again

I don't think it's the other injectors - this PR appears to fixe the problem only by changing the register polyfill (which from what I can tell is only used by the dynamic content script module)

> going through every dependency of `contentScript.ts` to ensure it doesn't have any side effects

I think this it the right approach for a couple reasons:

- We won't have the additional latency of the load in the micro-module case
- Modules are easier to reason about when importing does have side effects. Instagram has a post about this in their Python codebase: https://instagram-engineering.com/python-at-scale-strict-modules-c0bb9245c834

I'll go ahead and create a PR requiring explicit install of handlers, etc.

**Comment by fregante** [comment]
> this PR appears to fixe the problem only by changing the register polyfill

Does it do so consistently? To get multiple scripts injected I have to hard-reload the page multiple times, and even then they're injected by the dev tools because I can't replicate at all without the `devtools_page` field in manifest.

> I think this it the right approach for a couple reasons:

It's good to do in general, but using that as the **only** solution has several drawbacks:

- I don't think it's easily achievable at the moment, **any code** outside `init` in **any imported file** could cause problems. 
- It's easy to mess up in the future for the same reason
- The whole `contentScript.js` will still need to be parsed every single time you attempt injecting it, which could amount to whole seconds of lost CPU time.

Whereas injecting a lightweight file and `import()`ing the full version only adds 2.7ms in my test:

```

  console.time('import-time')
  import('./contentScriptReal').then(() => {
    console.timeEnd('import-time')
  });

**Comment by fregante** [comment]
> this PR appears to fixe the problem only by changing the register polyfill

This can be easily verified by adding some logging in `registerPolyfill` in `main` before the `executeScript` loop + additional logging before the `executeScript` call in `injectContentScript`

If it really _is_ happening due to the polyfill, ensure that it's not being `register`ed twice by adding a log inside `register()` as well.

**Comment by fregante** [comment]
👆 This https://github.com/pixiebrix/pixiebrix-extension/commit/333231729f36d8d6ed3f6e7af905933024f63728

Here's what happens for me:

0. Fresh install, enable a context script on a new page, like https://iframe-test-page.vercel.app/iframe.html
1. Extension loads
	2. LOG: `contentScripts.register`
3. I open a tab for https://iframe-test-page.vercel.app/iframe.html
	4. LOG: `contentScripts.register -> execute`
4. I open the dev tools
	5. Nothing happens
6. I refresh the page
	7. LOG: `contentScripts.register -> execute`
	8. LOG: `injectContentScript contentScript.js`
6. I refresh the page
	8. LOG: `injectContentScript contentScript.js`
	7. LOG: `contentScripts.register -> execute`

Things to notice:

- Opening the dev tools when the page is ready probably means that the content script is loaded so `injectContentScript` is never called
- injection happens twice, from 2 sources
- the injection order is unreliable
- `contentScripts.register` can't and won't detect injections by others

On a fresh install you can try running this version to double-check whether `contentScripts.register -> execute` is run twice (ensure that the page has no frames)

**Comment by twschiller** [comment]
Closing in favor of #557

**Comment by fregante** [comment]
For the record, I just tested this PR. At first it seemed to have fixed the issue, but further tries still showed it

Screen Shot 16

**Comment by twschiller** [comment]
Thanks for digging into this! I opened https://github.com/pixiebrix/pixiebrix-extension/pull/557 which supersedes this PR

Having the devtools open when visiting a page definitely is one way to reproduce the issue. I was also seeing it when I didn't have the devtools open, which is why I had tried the approach I had taken in this PR

#557 should avoid the double-install regardless of how the contentScript is injected

**Comment by twschiller** [comment]
> It's good to do in general, but using that as the **only** solution has several drawbacks:

Following up on this, as I somehow missed it vs. the other comment:
- I think it's relatively easy to catch during code review (or using linting rules). The rule would be `window.*.addListener` should not be at the top-level of a file

Let's definitely _also_ implement the async/dynamic load if the extra latency is that small. I think it might also improve memory utilization, as I'm not sure if Chrome/V8 is smart enough to garbage collect the extra content script code that never gets used

**Comment by fregante** [comment]
> Let's definitely _also_ implement the async/dynamic load if the extra latency is that small.

Sounds good! Can you open an issue about this and/or code splitting? Ensuring that the extension runs smoothly and is performant is probably where I can help you the most right now, whereas functionality would require more explanation.

**Pull request closed without merging**
