### PR TITLE
#5088 Change `useAutoFocus` to `useAutoFocusConfiguration` and default `focus` param to `false`

### LINKED ISSUE #5088: `useAutoFocus()` should not default to true
This causes weird behavior like the `Delay Millis` `NumberWidget` field in a sidebar panel foundation config focusing automatically when you open a sidebar extension in the page editor.

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #5088 

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer - @BALEHOK

### CODE REVIEW

**Review by fregante — CHANGES_REQUESTED** [review]
Having `useAutofocus`  default to `false` doesn't make sense. Functions shouldn't default to `noop`

```js
useAutoFocus(ref);
```

If I read this, I expect the field to be autofocused.

If the specific field doesn't need the autofocus by default, then _that_ field should use `focus: false`

**Comment by twschiller** [comment]
> Functions shouldn't default to noop

I tend to agree with @fregante here that we want to avoid misleading defaults

**Comment by BLoe** [comment]
I changed the hook name to `useAutoFocusConfiguration()` to hopefully remove the implication that it's affirmatively setting the widget to be focused when called.

**Review by BALEHOK — APPROVED** [review]
> I changed the hook name to useAutoFocusConfiguration()
Alternatively: `useConfigureAutofocus()`?

**Pull request merged**
