### PR TITLE
Return empty string onClear on SelectWidget

### PR DESCRIPTION
**Pull request by abdullah4244**
reference to this pr
https://github.com/pixiebrix/pixiebrix-app/pull/1764

### CODE REVIEW

**Comment by twschiller** [comment]
@BLoe @BALEHOK please review. Is this safe to do? Don't we have a defaultValue prop somewhere to control this?

**Comment by BLoe** [comment]
Yeah I think this should be left as `null`. What was the reason for this change? There's probably another way to accomplish the same thing.

**Comment by twschiller** [comment]
@BLoe Could you help advise on how this calling code in the app would need to be changed? https://github.com/pixiebrix/pixiebrix-app/pull/1764/files#diff-6f0eb2363b3f3d67f5ea977c4696700e6c72f3d1925ad57fdc5e0669dc62feabR175

**Comment by BLoe** [comment]
@twschiller @umair-pixiebrix I'm confused where the `<input/>` is coming from. `<SelectWidget/>` should be rendering a `<select/>` as far as I know, and I don't think there are any issues with that one having a null value. I might be totally missing something here though.

**Comment by twschiller** [comment]
@abdullah4244

>  we aren't making option value string here

If the user clears the value, your code will set the value to `""` where the code would be expecting an object. This will break any code that is expecting the value to be an object or `null`

We would have to change the types to be `CustomObject | ""` to reflect the values that can come from the form

> for example if we pass this option this select {label:Personal , value : {someKey :"some value"}} , select will have option Personal with value someKey : "someValue" but if we pass option {label:Personal , value : {} || value : [] || value : null} such as this it will be evaluated to {label:Personal , value : ""}

I'm not following this here `value : {} || value : [] || value : null` is it a typo? Could you clarify your comment?

**Comment by twschiller** [comment]
Closing to avoid introducing behavior for mixed value types

**Comment by BLoe** [comment]
The problem with handling `null` as a valid value here is that it interferes with how the `isClearable` functionality of the `<Select/>` widget works. If you can just use an empty string or a constant and then transform it before sending to the API, that would be best.

Here's an example where I've updated `<FieldTemplate/>` to handle a `null` value, and it breaks the "clearable" select:
https://www.loom.com/share/4589c2327adb4342a9214dcf31584e1d

**Pull request closed without merging**
