### PR TITLE
Revert "#814: optimistically load main page editor screen"

### PR DESCRIPTION
**Pull request by twschiller**
Reverts pixiebrix/pixiebrix-extension#832

### CODE REVIEW

**Comment by twschiller** [comment]
@fregante The work around for the issue you're running into for now is I think to not load the dev tools so on the initial activation? (Or not opening it up on the PixieBrix page)

The relevant sequence is:
1. You click "Link" to open app.pixiebrix.com
2. PixieBrix extension reads token from app.pixiebrix.com html
3. It uses that for future requests. I need to look to see where the dev tools looks for the token, and if it gates certain calls until it has that token

**Comment by fregante** [comment]
> * The PixieBrix app connects to the extension

It doesn't due to https://github.com/pixiebrix/pixiebrix-app/issues/202

Has this been merged/deployed into the app yet? https://github.com/pixiebrix/pixiebrix-extension/pull/714

Screen Shot 4

If it connected, this wouldn't be a problem. Chrome works fine

**Comment by fregante** [comment]
This can be closed, I'm able to use local-only version. 🎉 The 2 other blockers still apply: https://github.com/pixiebrix/pixiebrix-extension/issues/490#issuecomment-881637000

**Comment by twschiller** [comment]
> Has #714 been merged/deployed into the app yet?

@fregante the app is still behind, I'm hitting some compilation errors in the extension: https://github.com/pixiebrix/pixiebrix-app/pull/257. I'll probably need you're help soon to figure out the correct way to include the extension code as a dependency of the web app

**Pull request closed without merging**
