### PR TITLE
#7809: Fix Edge sidePanel links crash bug

### LINKED ISSUE #7809: MS Edge MV3 crashes when clicking sidebar gear icon
## Describe the bug

MS Edge MV3 crashes when clicking sidebar gear icon

## To Reproduce

1. Open the sidebar on an unrestricted page
2. Click the gear icon (button of death)

image

## Discussion

- Might need to use runtime.getURL? Is it the relative URL? https://github.com/pixiebrix/pixiebrix-extension/blob/583c480c6484faa0a4b9c3d5e7b1e25b2ba09f37/src/sidebar/Header.tsx#L101-L101
- The restricted URL content uses `browser.tabs.update`
- Clicking "Open Options" from the MS Edge Extension details page also works
- Other non-extension links work OK from the sidebar

## Actual behavior

Browser crashes/exits

## Expected behavior

Options page options

## Desktop (please complete the following information):

- OS: Mac 14.3.1 (23D60)
- Browser: Version 122.0.2365.63 (Official build) (arm64)
- Extension Version: 1.8.10-beta.2

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Probably fixes #7809

## Checklist

- [x] Designate a primary reviewer: @twschiller

### CODE REVIEW

**Comment by twschiller** [comment]
@fregante still crashing for me. I don't think that code is running? If I do the following it never gets hit:

image

**Comment by fregante** [comment]
122.0.2365.63

I can reproduce the crashing too, but only sometimes

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f8cf8334-892a-48a6-b277-f48d779bf0e5

**Comment by fregante** [comment]
`event.target` was _sometimes_ the SVG `path` element, so `link` was `false`.

**Comment by twschiller** [comment]
image

**Comment by twschiller** [comment]
> event.target was sometimes the SVG path element

Good catch

**Review by twschiller — APPROVED** [review]

**Pull request merged**
