### PR TITLE
Enable hot-module reload (the React app updates without reloading)

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/3012

Let's try again!

Note: If you use `web-ext`, append `--no-reload`

I already used it to prepare this PR, it was a breeze!

- https://github.com/pixiebrix/pixiebrix-extension/pull/7599

## Demo

The "watch" update time seems to be slower (6s -> 9s) though. Probably still worth it

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/9ebd6410-2c8f-4228-8f02-fb194a28eb5c

## Checklist

- [x] Test CSS changes too
- [ ] Verify that it doesn't cause ruckus in the background page
- [x] Verify MV3 support
- [ ] Figure out the level support of content scripts
- [ ] Restore "updated" notification, if still needed
- [x] Review config to ensure it's fully disabled in prod
- [ ] Look into [websocket error](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/876b2d35-e0fc-483d-922a-52131f9b1933) caused by HMR error overlay provider
- [ ] Update documentation
- [ ] Designate a primary reviewer

### CODE REVIEW

**Comment by grahamlangford** [comment]
@fregante Is there any reason this is still in open but in draft?

**Comment by fregante** [comment]
There are a few issues to iron out and I've been prioritizing other work.

I think I'll merge this as "optional" for now so that I can use it and improve on it, without breaking everyone's workflow in the meanwhile.

**Comment by fregante** [comment]
Ok this is ready to be merged.

- This is opt-in because it might have rough edges (like the occasional full-screen overlay showing unrelated errors)
- MV2 builds work
- MV3 builds work
- Production builds are unaffected
- It works in the page editor, sidebar, modals, etc, anything created by React

If you want to try, use one of:

- `npm run watch:webpack-hmr`
- `MV=3 npm run watch:webpack-hmr`

Neither one of these command includes typescript, so you'd have to run `npm run watch:typescript` separately.

_If_ you're using `web-ext run`, then use `web-ext run --no-reload` 

I can iterate on this while working on the extension itself. I already used it to bring some style changes recently.

**Review by fungairino — APPROVED** [review]
Please update contributing / setup wiki once merged please!

**Comment by fregante** [comment]
I don’t think it's quite ready for prime time yet so I don't want to waste your time debugging it yet. I'll be using this more often now and figure out if it's worth keeping or not before telling everyone. If it works well, it will just become the new default in the end.

**Pull request merged**
