### PR TITLE
#7327: Add modal UI to capture focus

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7327
- Related to https://github.com/pixiebrix/pixiebrix-extension/issues/7324
- Replaces https://github.com/pixiebrix/pixiebrix-extension/pull/7438

## Discussion

This PR creates a reusable/usable/styled component to capture the focus where necessary.

At this point it wraps the clipboard API and the `sidePanel.open()` API when initiated from the content script, restoring the ability to open the sidePanel at any part of the flow.

## Demo

Updated loom: https://www.loom.com/share/173dbae93e624ff9937dd389151d09f7

### Open sidePanel without immediate user gesture

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/999e3628-7e11-4fc2-879d-741f9d9636ec

as opposed to:

before

### Copy after focus loss

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/87f16d2b-fecf-4077-8d74-4e0b3882edf0

## Issues to resolve

- [x] Deal with multiple requests: probably await the focus but don't add another modal

## Checklist

- [ ] Add tests
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

**Comment by BrandonPxBx** [comment]
Are these components styled? This is a departure from the rest of our notices/types. If this is just functionality, looks good 👍

**Comment by fregante** [comment]
Yes they're styled. Somewhat similar to the notifications, but please propose a new style so I can apply it. I went with a purplish backdrop, a light box-shadow and rounded borders. The closest component visually is the notification.

**Review by BrandonPxBx — APPROVED** [review]
Don't have time to focus on the styling right now, and since this is a failsafe, it's good to go. Thanks @fregante

**Comment by fregante** [comment]
New style, it matches the notifications more closely:




https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/68e0881c-6064-4ce7-9335-b1a71d45aa17


I also added some logic to avoid multiple dialogs at once: 

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/26d868e5-8aee-4f21-8134-8aaf4f10874f

**Comment by twschiller** [comment]
@fregante looks like there's a conflict to fix before merging

**Pull request merged**
