### PR TITLE
Update package lock

### PR DESCRIPTION
**Pull request by BLoe**
I had to run `npm i` and pre-commit a few times, apparently because of some white space issues. I think it's good to go now.

### CODE REVIEW

**Comment by fregante** [comment]
My other PR already took care of this

**Comment by fregante** [comment]
Strange, I had specifically pushed these changes in https://github.com/pixiebrix/pixiebrix-extension/pull/1519 but I think the resolution enforcer is overriding them _sometimes_.

**Comment by twschiller** [comment]
Hmm, `npm ci` step still failing on:

```
Run npm ci
npm ERR! cssnano-preset-default not accessible from css-minimizer-webpack-plugin:cssnano

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-28T18_39_12_612Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by twschiller** [comment]
@BLoe  we might not need this PR anymore? I've merged in other PRs and the builds seem to be working properly

Also someone on our team seems to be using an old version of npm that uses package lock v1. Could you confirm which version of NPM you have installed?

**Comment by BLoe** [comment]
I'm on `7.20.3`, should I update to latest available with `nvm install node`?

**Pull request closed without merging**
